name: Dev Build

on:
  push:
    branches: [ dev ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: 'Create settings.xml'
        uses: s4u/maven-settings-action@v2.4.1
        with:
          githubServer: false
          servers: '[{"id": "promcteam", "username": "Travja", "password": "${{ secrets.GITHUB_TOKEN }}"}]'
      - name: Build with Maven
        run: mvn clean package -e
        env:
          GITHUB_TOKEN_REF: ${{ secrets.GH_PAT_FOR_ACTIONS_TOKEN }}
      - name: Publish artifact on GitHub Packages
        run: mvn clean deploy -e -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Notify Discord
        run: python ./.github/notify_published.py ${{ secrets.CORE_WEBHOOK }}
